const OK = 200;
const FOUND = 302;
const BAD_REQUEST = 400;
const NOT_FOUND = 404;
const METHOD_NOT_ALLOWED = 405;
const INTERNAL_SERVER_ERR = 500;
const SERVICE_UNAVAILABLE = 503;


module.exports = {
  OK,
  FOUND,
  BAD_REQUEST,
  NOT_FOUND,
  METHOD_NOT_ALLOWED,
  INTERNAL_SERVER_ERR,
  SERVICE_UNAVAILABLE
};
